### ISSUE TITLE
Branch 21.08 in flathub seems outdated

### ISSUE THREAD

**Issue by peacememories** [flathub/org.freedesktop.Sdk.Extension.haskell#67]
Hi, thanks for maintaining this sdk. And sorry if this is the wrong place to file this issue.
I need one of the fixes that have been recently added to this repo. namely the libnuma fix. This seems to be checked in here, but when I do a `flathub remote-info` on branch `21.08` the last commit listed there is `removed incorrect version attribute of module cabal (fa5c91a2)`. Branch 20.08 has the latest fix, but when I install that, I get the note `Requested SDK extension "haskell" is not installed`.

I'm not sure what's going on there, to be honest

**Comment by ghost** [comment]
In branch 21.08 GHC wasn't up-to-date, but libnuma has been fixed in both branches. ([20.08](https://github.com/flathub/org.freedesktop.Sdk.Extension.haskell/commit/a12d277406e7434c3e9b1933c5fd2023380aae94) and [21.08](https://github.com/flathub/org.freedesktop.Sdk.Extension.haskell/commit/4627d55ba8561fd6fe5aca3b193f4e2afc582b31))
If you're still having problems with the SDK, feel free to reach out.

**Comment by peacememories** [comment]
This is what i mean:
```bash
$ flatpak remote-info flathub org.freedesktop.Sdk.Extension.haskell/x86_64/21.08
Remote ‘flathub’ found in multiple installations:

   1) system
   2) user

Which do you want to use (0 to abort)? [0-2]: 2
        ID: org.freedesktop.Sdk.Extension.haskell
       Ref: runtime/org.freedesktop.Sdk.Extension.haskell/x86_64/21.08
      Arch: x86_64
    Branch: 21.08
Collection: org.flathub.Stable
  Download: 423.4 MB
 Installed: 2.7 GB

    Commit: bb3fcc4f0f218da0331adabe4ad28e3f47de445e1cd66dcf20d25e527a48cff2
    Parent: 113b24f05526382fad56e96134b1625bad76fd51bc871866f43e9cecbd579368
   Subject: removed incorrect version attribute of module cabal (fa5c91a2)
      Date: 2021-11-16 20:14:30 +0000

```
(the result for `system` is the same)

For some reason, the flathub repository does not provide me with the latest version that's in this repository. I'm fairly certain that's not a problem of this repo, but I haven't seen it anywhere else and have no idea what's causing this.
I'm fairly new to flatpak, to be fair.

**Comment by ghost** [comment]
You're right, the latest build in the remote is outdated. Apparently, the new build never got published on flathub. I'm currently waiting if the new build shows up, otherwise I'm opening an issue.

**Comment by peacememories** [comment]
Seems to be working, thanks :)
