### ISSUE TITLE
Include hls?

### ISSUE THREAD

**Issue by peacememories** [flathub/org.freedesktop.Sdk.Extension.haskell#68]
Since this sdk extension is to be used as an alternative to GHCup, and many editor extensions, e.g. VSCode seem to expect GHCup to handle installing the haskell language server, it might be good to include it in this sdk extension.
Currently I'm running into a problem since this extension has been updated to 9.2.2. that VSCode does not have a suitable hls implementation anymore.

**Comment by peacememories** [comment]
Alternatively, would it be possible to provide more than one version of haskell at a time? I guess this would need to be done with different extension packages?

**Comment by ghost** [comment]
I'm quite busy atm, but you could include hls and open a pull request. You can find information how to build flatpaks [here](https://docs.flatpak.org/en/latest/).

> Alternatively, would it be possible to provide more than one version of haskell at a time? I guess this would need to be done with different extension packages?

There are a few SDK extensions that do that (for major versions), but imo that is out of scope for this project.
In general, you can [install specific version of flatpaks](https://github.com/flatpak/flatpak/issues/3097#issuecomment-530583469), but v9.2.1 with the libnuma fix is missing in the remote.

**Comment by peacememories** [comment]
I can try adding hls. Right now I'm struggling to build it at all with 9.2.2, so that's gonna be... fun, but I'll see what I can do. Alternatively I could create a sibling package specifically for haskell 9.2.1, though I'm very new to flatpak so I'm not sure I'd be a good maintainer for that^^

**Comment by peacememories** [comment]
Also you're right, for patch versions this seems kind of excessive

**Comment by ghost** [comment]
You can now (temporarily) downgrade to 9.2.1 using [this command](https://github.com/flathub/org.freedesktop.Sdk.Extension.haskell/pull/69#issuecomment-1094256176):
`flatpak install --user https://dl.flathub.org/build-repo/83555/org.freedesktop.Sdk.Extension.haskell.flatpakref`.
As soon as hls works with the current version, you can change back to the official repo.
